%%%v
%%% createrPBSfile.m
%%%
%%% Writes out a script that runs our ECCO calculation scripts via an SGE
%%% job.
%%%
function sgefname = createSGEfile (dirname,nodes,queue,email,funcname,n)

  %%% Set variables correctly for PBS
  headertext = [...
  '#!/bin/sh \n' ...
  '# \n' ...
  '# Your job name \n' ...
  '#$ -N ',funcname,'(',num2str(n),')\n' ...
  '# \n' ...
  '# Use current working directory \n' ...
  '#$ -cwd \n' ...
  '# \n' ...
  '# Join stdout and stderr \n' ...
  '#$ -j y \n' ...
  '# \n' ...
  '# Select queue \n' ...
  '#$ -q ',queue,' \n' ...
  '# \n' ...
  '# pe request for MPI. Set your number of processors here. \n' ...
  '# Make sure you use the "impi" parallel environment. \n' ...
  '#$ -pe impi ',num2str(nodes),' \n' ...
  '# \n' ...
  '# Run job through bash shell \n' ...
  '#$ -S /bin/bash \n' ...
  '# \n' ...
  '## Output file \n' ...
  '#$ -o ./output.txt \n' ...
  '#\n' ...
  '# Email address for updates on job progress \n' ...
  '#$ -M ',email,'\n' ...
  '#\n' ...
  '# The following is for reporting only. It is not really needed \n' ...
  '# to run the job. It will show up in your output file. \n' ...
  '# echo "Got $NSLOTS processors." \n' ...
  '# echo "Machines:" \n' ...
  '# cat $TMPDIR/machines \n' ...
  '# \n' ...
  '# Use full pathname to make sure we are using the right mpirun \n' ...
  '# Gridengine will set NSLOTS and TMPDIR for you \n' ...  
  'cd ..\n' ...
  'matlab -singleCompThread -r \"',funcname,'(',num2str(n),')\" > ',funcname,'_',num2str(n),'_output.txt'];

  %%% Open output script and write header text
  sgefname = ['run_',funcname,'_',num2str(n)];
  wfid = fopen(fullfile(dirname,sgefname),'w');
  if (wfid == -1)
    error('Could not open PBS script file');
  end
  fprintf(wfid,headertext); 
  
  %%% Close files when we're done
  fclose(wfid);

end

